apiVersion: v1
kind: ConfigMap
metadata:
  name: northstar-notification-service-configmap
data:
  active-profile: "default"
  openapi-gateway-url: "http://northstar-gateway-service-svc:8181/api/notification"
  base-url: "http://northstar-gateway-service-svc:8181"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: northstar-notification-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: northstar-notification-service-deployment
  template:
    metadata:
      labels:
        app: northstar-notification-service-deployment
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: "-XX:TieredStopAtLevel=1 -noverify -Xms128m -Xmx512m -Xss4m -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1"
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: active-profile
                  name: northstar-notification-service-configmap
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: northstar-notification-service-configmap
                  key: base-url
            - name: DISCOVERY_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: northstar-discovery-service-configmap
                  key: discovery-server-url
            - name: OPENAPI_GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: northstar-notification-service-configmap
                  key: openapi-gateway-url
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: northstar-notification-service-db-configmap
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: northstar-notification-service-db-configmap
                  key: db-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: northstar-notification-service-db-configmap
                  key: db-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: northstar-notification-service-db-secret
                  key: db-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: northstar-notification-service-db-secret
                  key: db-pass
          image: northstar-notification-service:latest
          imagePullPolicy: IfNotPresent
          name: northstar-notification-service
          ports:
            - containerPort: 8190
              protocol: TCP
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: northstar-notification-service-svc
spec:
  selector:
    app: northstar-notification-service-deployment
  ports:
    - protocol: TCP
      port: 8190
      targetPort: 8190
  type: ClusterIP
